config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'about' => 'top#about', as: 'about'

  resources :members, only: [:index, :show] do
    get 'search', on: :collection
    resources :entries, only: :index
  end

  resources :articles, only: [:index, :show] do
    resources :comments, only: :create
    get 'search', on: :collection
  end

  resources :entries do
    resources :comments, only: :create
    patch 'like', 'unlike', on: :member
    get 'voted', on: :collection
    resources :images, controller: 'entry_images' do
      patch :move_higher, :move_lower, on: :member
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]

  namespace :admin do
    root 'top#index'
    resources :members do
      get 'search', on: :collection
      get 'download', on: :collection, as: 'download'
    end
    resources :articles do
      resources :comments, only: :create
      get 'search', on: :collection
    end
    resources :activity_logs, only: :index do
      get 'download', on: :collection, as: 'download'
    end
  end

end

app/models/entry_image.rb
class EntryImage < ApplicationRecord
  belongs_to :entry
  has_one_attached :data
  acts_as_list scope: :entry

  attribute :new_data

  validates :new_data, presence: { on: :create }

  validate if: :new_data do
    if new_data.respond_to?(:content_type)
      errors.add(:new_data, :invalid_image_type) unless new_data.content_type.in?(ALLOWED_CONTENT_TYPES)
    else
      errors.add(:new_data, :invalid)
    end
  end

  before_save do
    self.data = new_data if new_data
  end
end

app/controllers/entry_images_controller.rb
class EntryImagesController < ApplicationController
  before_action :login_required
  before_action :set_entry_image

  def index
    @images = @entry.images.order :position
  end

  def new
    @image = @entry.images.build
  end

  def create
    @image = @entry.images.build image_params
    if @image.save
      redirect_to entry_images_path(@entry), notice: '画像を作成しました'
    else
      render :new
    end
  end

  def show
    redirect_to action: :edit
  end

  def edit
    @image = @entry.images.find params[:id]
  end

  def update
    @image = @entry.images.find params[:id]
    @image.assign_attributes image_params
    if @image.save
      redirect_to entry_images_path, notice: '画像を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @image = @entry.images.find params[:id]
    @image.destroy
    redirect_to entry_images_path, notice: '画像を削除しました'
  end

  def move_higher
    @image = @entry.images.find params[:id]
    @image.move_higher
    redirect_back fallback_location: entry_images_path
  end

  def move_lower
    @image = @entry.images.find params[:id]
    @image.move_lower
    redirect_back fallback_location: entry_images_path
  end

  private

  def set_entry_image
    @entry = current_member.entries.find params[:entry_id]
  end

  def image_params
    params.require(:entry_image).permit(:new_data, :alt_text)
  end
end

app/views/entry_images/_form.html.haml
= render 'shared/errors', obj: @image
%table.attr
  %tr
    %th= form.label :new_data
    %td
      %div= form.file_field :new_data
      = image_tag '', id: 'thumbnail', accept: 'image/*', style: 'width: 100px'
  %tr
    %th= form.label :alt_text
    %td= form.text_field :alt_text, size: 40

app/views/entry_images/edit.html.haml
- @page_title = 'ブログ記事の画像編集'
%h1= @page_title

%h2= @entry.title

= form_with model: @image, as: 'image', url: entry_image_path(@entry, @image), class: 'entry-image-form' do |form|
  = render 'form', form: form
  .entry-image-form-submit= form.submit

app/views/entry_images/index.html.haml
- @page_title = 'ブログ記事の画像'
%h1= @page_title

%h2= @entry.title

%ul.toolbar
  = menu_link_to 'ブログ記事に戻る', entry_path(@entry)
  = menu_link_to '画像の追加', new_entry_image_path(@entry)

- if @images.present?
  %table.list
    %thead
      %tr
        %th 番号
        %th 画像
        %th 代替テキスト
        %th 操作
    %tbody
      - @images.each_with_index do |image, index|
        %tr
          %td= index + 1
          %td
            = image_tag image.data.variant(resize: '100x>'), alt: image.alt_text
          %td
            = image.alt_text
          %td
            %div
              = link_to '編集', edit_entry_image_path(@entry, image)
              |
              = link_to '削除', entry_image_path(@entry, image), method: :delete, data: { confirm: '本当に削除しますか？' }
            %div
              = link_to_if index > 0, '上へ', move_higher_entry_image_path(@entry, image), method: :patch
              |
              = link_to_if index < @images.size - 1, '下へ', move_lower_entry_image_path(@entry, image), method: :patch
- else
  %p 画像がありません

app/views/entry_images/new.html.haml
- @page_title = 'ブログ記事への画像追加'
%h1= @page_title

%h2= @entry.title

= form_with model: @image, as: 'image', url: entry_images_path(@entry, @image), class: 'entry-image-form' do |form|
  = render 'form', form: form
  .entry-image-form-submit= form.submit