config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'about' => 'top#about', as: 'about'

  resources :members, only: [:index, :show] do
    get 'search', on: :collection
    resources :entries, only: :index
  end

  resources :articles, only: [:index, :show] do
    resources :comments, only: :create
    get 'search', on: :collection
  end

  resources :entries do
    resources :comments, only: :create
    patch 'like', 'unlike', on: :member
    get 'voted', on: :collection
    resources :images, controller: 'entry_images' do
      patch :move_higher, :move_lower, on: :member
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]

  namespace :admin do
    root 'top#index'
    resources :members do
      get 'search', on: :collection
      get 'download', on: :collection, as: 'download'
    end
    resources :articles do
      resources :comments, only: :create
      get 'search', on: :collection
    end
    resources :activity_logs, only: :index do
      get 'download', on: :collection, as: 'download'
    end
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
  STATUS_VALUES = %w[draft member_only public].freeze

  belongs_to :author, class_name: 'Member', foreign_key: 'member_id'
  has_many :images, class_name: 'EntryImage'
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :member
  has_many :entry_comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 200 }
  validates :body, :posted_at, presence: true
  validates :status, inclusion: { in: STATUS_VALUES }

  scope :common, -> { where(status: 'public') }
  scope :published, -> { where('status <> ?', 'draft') }
  scope :full, ->(member) { where('status <> ? OR member_id = ?', 'draft', member.id) }
  scope :readable_for, ->(member) { member ? full(member) : common }
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :login_required, except: %i[index show]
  after_action :create_entry_log, only: :create
  after_action :remove_entry_log, only: :destroy

  def index
    if params[:member_id]
      @member = Member.find params[:member_id]
      @entries = @member.entries
    else
      @entries = Entry.all
    end

    @entries = @entries.includes(:author).readable_for(current_member).order(posted_at: :desc).page(params[:page]).per(5)
  end

  def new
    @entry = Entry.new(posted_at: Time.now)
  end

  def create
    @entry = Entry.new(entry_permit_params)
    if @entry.save
      redirect_to entry_path(@entry), notice: 'ブログを作成しました'
    else
      flash.now[:alert] = 'ブログの作成に失敗しました'
      render :new
    end
  end

  def show
    @entry = Entry.readable_for(current_member).find params[:id]
    @entry = @entry.decorate
  end

  def edit
    @entry = current_member.entries.find params[:id]
  end

  def update
    @entry = current_member.entries.find params[:id]
    @entry.assign_attributes(entry_permit_params)
    if @entry.save
      redirect_to entry_path(@entry), notice: 'ブログを更新しました'
    else
      flash.now[:alert] = 'ブログの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @entry = current_member.entries.find params[:id]
    @entry.destroy
    redirect_to entries_path, notice: 'ブログを削除しました'
  end

  def like
    @entry = Entry.published.find params[:id]
    current_member.voted_entries << @entry
    redirect_to entry_path(@entry), notice: '投票しました'
  end

  def unlike
    current_member.voted_entries.destroy(Entry.find(params[:id]))
    redirect_to voted_entries_path, notice: '投票を取り消しました'
  end

  def voted
    @entries = current_member.voted_entries.published.includes(:author).order('votes.created_at DESC').page(params[:page]).per(15)
  end

  private

  def entry_permit_params
    params.require(:entry).permit(:member_id, :title, :body, :posted_at, :status).merge(author: current_member)
  end

  def create_entry_log
    ActivityLog.create! log_type: :create_entry, performer: current_member, performed_at: Time.now, performed_title: @entry.title
  end

  def remove_entry_log
    ActivityLog.create! log_type: :remove_entry, performer: current_member, performed_at: Time.now, performed_title: @entry.title
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def the_first_image(entry)
    image = entry.images.order(:position)[0]

    render_entry_image(image) if image
  end

  def other_images(entry)
    buffer = ''.html_safe

    entry.images.order(:position)[1..-1]&.each do |image|
      buffer << render_entry_image(image)
    end

    buffer
  end

  private

  def render_entry_image(image)
    tag.div do
      image_tag image.data.variant(resize: '530x>'), alt: image.alt_text, style: 'display: block; margin: 0 auto 15px'
    end
  end
end

app/views/entries/_comment_form.html.haml
- @page_title = 'コメント'

%h1= @page_title

.comment-form-ids{:id => "comment-form-entry-#{@entry.id.to_s}"}
  = form_with model: [@entry, Comment.new], class: 'entry-comment-form' do |f|
    = f.hidden_field :commenter_id, value: current_member.id
    = f.hidden_field :commenter_type, value: current_member.class
    = f.hidden_field :entry_id, value: @entry.id
    = f.text_field :body, class: "entry-comment-form-field", placeholder: "コメント ...", autocomplete: :off
    = f.submit '投稿する'

%div{id: "comment-entry-#{@entry.id.to_s}"}
  = render 'comment_list', { entry: @entry }

app/views/entries/_comment_list.html.haml
- entry.entry_comments.includes(:commenter).each do |comment|
  .mb-2
    %span
      %strong
        = comment.commenter.name
    %span= comment.body
    %span= comment.commented_date

app/views/entries/_footer.html.haml
%ul.entry-footer
  - if current_member
    %li= EntryDecorator.status_text(entry.status)
    - if current_member == entry.author
      = menu_link_to '編集', edit_entry_path(entry)
      = menu_link_to '画像', entry_images_path(entry)
      = menu_link_to '削除', "/entries/#{entry.id}", method: :delete, data: { confirm: '本当に削除しますか？' }
  %li
    write by
    = link_to entry.author.name, member_entries_path(entry.author)
  %li
    = entry.posted_date
  - if (count = entry.votes.count) > 0
    %li
      %span.vote
        ★#{count}

app/views/entries/_form.html.haml
= render 'shared/errors', obj: @entry

%table.attr
  %tr
    %th{width: '80'}= form.label :title
    %td= form.text_field :title, size: 50
  %tr
    %th= form.label :body
    %td= form.text_area :body, rows: 10, cols: 45
  %tr
    %th= form.label :posted_at, for: 'entry_posted_at_1i'
    %td= form.datetime_select :posted_at, start_year: 2000, end_year: Time.now.year + 1, use_month_numbers: true
  %tr
    %th= form.label :status
    %td= form.select :status, EntryDecorator.status_options

app/views/entries/_votes.html.haml
.vote
  - @entry.voters.order("votes.created_at").each do |voter|
    ★#{voter.name}
  - if current_member && current_member.votable_for?(@entry)
    = link_to "★いいね!", like_entry_path(@entry), method: :patch, class: "button"

app/views/entries/edit.html.haml
- @page_title = 'ブログ記事の編集'
%h1= @page_title

.toolbar= link_to '記事の表示に戻る', entry_path(@entry)

= form_with model: @entry, local: true, class: 'entry-form' do |form|
  = render 'form', form: form
  .entry-form-submit= form.submit

app/views/entries/index.html.haml
- @page_title = @member ? @member.name + 'さんのブログ' : '会員のブログ'
%h1= @page_title

- if current_member
  .toolbar
    = menu_link_to 'ブログ記事の作成', new_entry_path
    |
    = menu_link_to '投票した記事', voted_entries_path
- if @entries.present?
  - @entries.decorate.each do |entry|
    %h2= entry.title
    %p
      = truncate(entry.body, length: 80)
      = link_to 'もっと読む', entry_path(entry)
    = render 'footer', entry: entry
  = paginate @entries
- else
  %p 記事がありません

app/views/entries/new.html.haml
- @page_title = "ブログ記事の新規作成"
%h1= @page_title
= form_with model: @entry, local: true do |form|
  = render "form", form: form
  .entry-form-submit= form.submit

app/views/entries/show.html.haml
- @page_title = @entry.title + ' - ' + @entry.author.name + 'さんのブログ'

%h1
  = @entry.author.name
  さんのブログ
%h2= @entry.title
= the_first_image(@entry)
= simple_format(@entry.body)
= other_images(@entry)
= render 'footer', entry: @entry
= render "votes"

- if current_member.present?
  = render 'comment_form'

app/views/entries/voted.html.haml
- @page_title = '投票した記事'
%h1= @page_title

- if @entries.present?
  %ul
    - @entries.each do |entry|
      %li
        = link_to entry.title, entry
        by
        = link_to entry.author.name, member_entries_path(entry.author)
        = link_to '削除', unlike_entry_path(entry), method: :patch, data: { confirm: '削除しますか?' }
  = paginate @entries
- else
  %p 記事がありません。