config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'about' => 'top#about', as: 'about'

  resources :members, only: [:index, :show] do
    get 'search', on: :collection
    resources :entries, only: :index
  end

  resources :articles, only: [:index, :show] do
    resources :comments, only: :create
    get 'search', on: :collection
  end

  resources :entries do
    resources :comments, only: :create
    patch 'like', 'unlike', on: :member
    get 'voted', on: :collection
    resources :images, controller: 'entry_images' do
      patch :move_higher, :move_lower, on: :member
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]

  namespace :admin do
    root 'top#index'
    resources :members do
      get 'search', on: :collection
      get 'download', on: :collection, as: 'download'
    end
    resources :articles do
      resources :comments, only: :create
      get 'search', on: :collection
    end
    resources :activity_logs, only: :index do
      get 'download', on: :collection, as: 'download'
    end
  end

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_comments, dependent: :destroy

  validates :title, :body, :released_at, presence: true
  validates :title, length: { maximum: 80 }
  validates :body, length: { maximum: 2000 }

  before_validation do
    self.expired_at = nil if @no_expiration
  end

  validate do
    errors.add(:expired_at, :expired_at_too_old) if expired_at && expired_at < released_at
  end

  scope :open_to_the_public, -> { where(member_only: false) }

  scope :visible, lambda {
    now = Time.now
    where('released_at <= ?', now).where('expired_at > ? OR expired_at IS NULL', now)
  }

  def no_expiration
    expired_at.nil?
  end

  def no_expiration=(val)
    @no_expiration = val.in?([true, '1'])
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::Base
  before_action :admin_login_required
  before_action :set_article, only: %i[show edit update destroy]
  after_action :create_article_log, only: :create
  after_action :remove_article_log, only: :destroy

  def index
    @articles = Article.order(released_at: :desc).page(params[:page]).per(15)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_permit_params
    if @article.save
      redirect_to admin_articles_path, notice: 'ニュース記事を登録しました'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update article_permit_params
      redirect_to admin_articles_path, notice: 'ニュース記事を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_articles_path, notice: 'ニュース記事を削除しました'
  end

  def search
    @article_search_form = ArticleSearchForm.new article_search_params
    @articles = @article_search_form.search params[:q]
    @articles = @articles.order(released_at: :desc).page(params[:page]).per(15)
    render :index
  end

  private

  def set_article
    @article = Article.find(params[:id]).decorate
  end

  def article_permit_params
    params.require(:article).permit(:title, :body, :released_at, :no_expiration, :expired_at, :member_only)
  end

  def article_search_params
    params.permit(:title)
  end

  def create_article_log
    ActivityLog.create! log_type: :create_article, performer: current_member, performed_at: Time.now, performed_title: @article.title
  end

  def remove_article_log
    ActivityLog.create! log_type: :remove_article, performer: current_member, performed_at: Time.now, performed_title: @article.title
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.visible.order(released_at: :desc)
    @articles = @articles.open_to_the_public unless current_member
    @articles = @articles.page(params[:page]).per(5)
  end

  def show
    articles = Article.visible
    articles.open_to_the_public unless current_member
    @article = Article.find(params[:id]).decorate
  end

  def search
    @article_search_form = ArticleSearchForm.new article_search_params
    @articles = @article_search_form.search params[:q]
    @articles = @articles.order(released_at: :desc).page(params[:page]).per(15)
    render :index
  end

  private

  def article_search_params
    params.permit(:title)
  end
end

app/views/admin/articles/_form.html.haml
= render 'shared/errors', obj: @article

%table.attr
  %tr
    %th= form.label :title
    %td= form.text_field :title, size: 20
  %tr
    %th= form.label :body
    %td= form.text_area :body, rows: 10, cols: 45
  %tr
    %th= form.label :released_at, for: 'article_released_at_1i'
    %td= form.datetime_select :released_at, start_year: 2000, end_year: Time.now.year + 1, use_month_numbers: true
  %tr
    %th= form.label :expired_at, for: 'article_expired_at_1i'
    %td
      %div
        = form.check_box :no_expiration
        = form.label :no_expiration
      #article_expired_at
        = form.datetime_select :expired_at, start_year: 2000, end_year: Time.now.year + 1, use_month_numbers: true
  %tr
    %th= Article.human_attribute_name(:member_only)
    %td
      = form.check_box :member_only
      = form.label :member_only

app/views/admin/articles/edit.html.haml
- @page_title = 'ニュース記事の編集'
%h1= @page_title

%p= link_to '記事の詳細に戻る', admin_article_path(@article)

= form_with model: [:admin, @article], local: true, class: 'article-form' do |form|
  = render 'form', form: form
  .article-form-submit= form.submit

app/views/admin/articles/index.html.haml
- @page_title = 'ニュース記事一覧'

= form_with url: search_admin_articles_path, local: true, method: :get, class: 'article-search-form' do |f|
  = f.text_field 'q', size: 25, placeholder: 'タイトルを入力してください', class: 'article-search-field'
  = f.submit '検索', class: 'article-search-form-submit'

%h1= @page_title
.toolbar= link_to '新規作成', new_admin_article_path

- if @articles.present?
  %table.list
    %thead
      %tr
        %th タイトル
        %th 日時
        %th 操作
    %tbody
      - @articles.decorate.each do |article|
        %tr
          %td= link_to article.title, admin_article_path(article)
          %td= article.released_date
          %td
            = link_to '編集', edit_admin_article_path(article)
            |
            = link_to '削除', "/admin/articles/#{article.id}", method: :delete, data: { confirm: '本当に削除しますか?' }
  = paginate @articles

app/views/admin/articles/new.html.haml
- @page_title = 'ニュース記事の新規登録'
%h1= @page_title

= form_with model: [:admin, @article], local: true, class: 'article-form' do |form|
  = render 'form', form: form
  .article-form-submit= form.submit

app/views/admin/articles/show.html.haml
- @page_title = @article.title

%h1= @article.title

- if current_member
  .toolbar= link_to '編集', edit_admin_article_path(@article)
%table.attr
  %tr
    %th{width: '100'} タイトル
    %td= @article.title
  %tr
    %th 本文
    %td= simple_format(@article.body)
  %tr
    %th 掲載開始日時
    %td= @article.released_date
  %tr
    %th 掲載終了日時
    %td= @article.expired_date
  %tr
    %th 会員限定
    %td= @article.member_only_display