config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'about' => 'top#about', as: 'about'

  resources :members, only: [:index, :show] do
    get 'search', on: :collection
    resources :entries, only: :index
  end

  resources :articles, only: [:index, :show] do
    resources :comments, only: :create
    get 'search', on: :collection
  end

  resources :entries do
    resources :comments, only: :create
    patch 'like', 'unlike', on: :member
    get 'voted', on: :collection
    resources :images, controller: 'entry_images' do
      patch :move_higher, :move_lower, on: :member
    end
  end

  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]

  namespace :admin do
    root 'top#index'
    resources :members do
      get 'search', on: :collection
      get 'download', on: :collection, as: 'download'
    end
    resources :articles do
      resources :comments, only: :create
      get 'search', on: :collection
    end
    resources :activity_logs, only: :index do
      get 'download', on: :collection, as: 'download'
    end
  end

end

app/views/shared/_admin_menubar.html.haml
%nav#admin-menubar.menubar
  %ul
    = menu_link_to '管理TOP', admin_root_path
    = menu_link_to '会員管理', admin_members_path
    = menu_link_to 'アクティビティログ', admin_activity_logs_path
    = menu_link_to 'ニュース記事管理', admin_articles_path
    = menu_link_to 'TOP', root_path

app/views/shared/_errors.html.haml
- if obj.errors.present?
  #errors
    %h3 エラーがあります
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.haml
= link_to 'このサイトについて', about_path
| Copyright (C) Baseball CMS 2019

app/views/shared/_header.html.haml
= image_tag 'logo.png', size: '272x48', alt: 'Baseball CMS'
- if current_member
  %ul.account-menu
    = menu_link_to current_member.name + 'さん', account_path(current_member)
    |
    = menu_link_to 'ログアウト', :session, method: :delete, data: { confirm: 'ログアウトしますか？' }

- if controller.kind_of?(Admin::Base)
  = render "shared/admin_menubar"
- else
  = render "shared/menubar"

app/views/shared/_login_form.html.haml
%h2 ログイン
= form_with url: '/session', id: 'login-form', local: true do |f|
  %div
    = f.label 'ユーザー名：'
    = f.text_field :name
  %div
    = f.label 'パスワード：'
    = f.password_field :password
  %div
    = f.submit 'ログイン'

app/views/shared/_member_form.html.haml
= render 'shared/errors', obj: @member
%table.attr
  %tr
    %th{width: '200'}= form.label :new_profile_picture
    %td
      %div= form.file_field :new_profile_picture
      = image_tag '', id: 'thumbnail', accept: 'image/*', style: 'width: 100px'
      - if @member.profile_picture.attached?
        %div
          = image_tag @member.profile_picture.variant(resize: '128x128')
          = form.check_box :remove_profile_picture
          = form.label :remove_profile_picture
  %tr
    %th= form.label :number
    %td= form.text_field :number
  %tr
    %th= form.label :name
    %td= form.text_field :name
  %tr
    %th= form.label :full_name
    %td= form.text_field :full_name
  %tr
    %th= Member.human_attribute_name(:sex)
    %td
      = form.radio_button :sex, :male
      = form.label :sex_1
      = form.radio_button :sex, :female
      = form.label :sex_2
  %tr
    %th= form.label :birthday, for: 'member_birthday_1i'
    %td= form.date_select :birthday, start_year: 1940, end_year: Time.current.year, use_month_numbers: true
  %tr
    %th= form.label :prefecture_id
    %td= form.collection_select :prefecture_id, Prefecture.all, :id, :name
  %tr
    %th= form.label :email
    %td= form.text_field :email
  - if @member.new_record?
    %tr
      %th= Member.human_attribute_name(:password)
      %td= form.password_field :password
    %tr
      %th= Member.human_attribute_name(:password_confirmation)
      %td= form.password_field :password_confirmation
  - if controller.kind_of?(MembersController)
    %tr
      %th= Member.human_attribute_name(:administrator)
      %td
        = form.check_box :administrator
        = form.label :administrator
  - if controller.kind_of?(Admin::MembersController)
    %tr
      %th= Member.human_attribute_name(:administrator)
      %td
        = form.check_box :administrator
        = form.label :administrator

app/views/shared/_menubar.html.haml
%nav.menubar
  %ul
    = menu_link_to 'TOP', root_path
    = menu_link_to 'ニュース', articles_path
    = menu_link_to 'ブログ', entries_path
    - if current_member
      = menu_link_to '会員名簿', members_path
      - if current_member.administrator?
        = menu_link_to '管理ページ', admin_root_path

app/views/shared/_sidebar.html.haml
= render 'shared/login_form' unless current_member
%h2 最新ニュース
- articles = Article.visible.order(released_at: :desc).limit(5)
- articles = articles.open_to_the_public unless current_member
%ul
  - articles.each do |article|
    %li= link_to article.title, article_path(article)
%h2 会員のブログ
- entries = Entry.includes(:author).readable_for(current_member).order(posted_at: :desc).limit(5)
%ul
  - entries.each do |entry|
    %li
      = link_to entry.title, entry_path(entry)
      write by
      =link_to entry.author.name, member_entries_path(entry.author)